### ISSUE TITLE
Invalid tag for v0.8.84

### ISSUE THREAD

**Issue by jacobemcken** [grzm/awyeah-api#13]
The `README.md` suggests using the following to include the dependency:
```clojure
com.grzm/awyeah-api {:git/url "https://github.com/grzm/awyeah-api"
                     :git/sha "e5513349a2fd8a980a62bbe0d45a0d55bfcea141"
                     :git/tag "v0.8.84"}
```

But doing so from a Babashka script results in:
```
Error building classpath. Library com.grzm/awyeah-api has invalid tag: v0.8.84
Exception in thread "main" clojure.lang.ExceptionInfo:  babashka.process.Process@7b5903e0
	at babashka.process$check.invokeStatic(process.cljc:111)
        ...
```

**Comment by cursive-ide** [comment]
The same happens from a standard `deps.edn`.

**Comment by borkdude** [comment]
The tag doesn't seem to exist: https://github.com/grzm/awyeah-api/tags
but if you leave out the tag, the dep should still work in deps.edn / bb.edn with a full sha.

**Comment by borkdude** [comment]
ping @grzm

**Comment by grzm** [comment]
Pushed. Thanks for the report!
