### ISSUE TITLE
Error SignatureDoesNotMatch on Digitalocean(custom endpoint)

### ISSUE THREAD

**Issue by mamolli** [grzm/awyeah-api#3]
When invoking s3 (or other services) for digitalocean, but I expect the problem might extend to all other custom s3 backends, I am getting an error. The same invoke works without errors for jvm clojure aws-api.

Snippet included:

```
(def s3-client (aws/client {:api :s3
                            :endpoint-override 
                            {:protocol :https
                             :hostname "fra1.digitaloceanspaces.com"}
                            :credentials-provider
                            (credentials/basic-credentials-provider
                             ;; secondary key
                              {:access-key-id     "XXX"
                               :secret-access-key "XXX"})}))
  
  
(aws/invoke s3-client {:op :ListBuckets})
```

```
{:Error {:Code "SignatureDoesNotMatch",
         :CodeAttrs {},
         :HostId "2b9e7d16-fra1a-fra1",
         :HostIdAttrs {},
         :RequestId "tx00000000000000a6c056b-0063685958-2b9e7d16-fra1a",
         :RequestIdAttrs {}},
 :ErrorAttrs {},
 :cognitect.anomalies/category :cognitect.anomalies/forbidden}
```

**Comment by patbrown** [comment]
Having DO issues with cognitect's api is not new. For a brief period the steps here were working for me.
[aws-api issue 150](https://github.com/cognitect-labs/aws-api/issues/150)

It no longer does. I've since moved away from using DO spaces, but the issue linked is a great starting point.

**Comment by grzm** [comment]
Closing as this does not work in aws-api either, and fixing it would likely require an additional divergence from the aws-api codebase.
